### ISSUE TITLE
Gamakay/Womier K61 

### ISSUE THREAD

**Issue by ghost** [qmk/qmk.fm_old#148] opened 2022-01-15 00:59 UTC
### Description

I'm new to all this, and got my first keyboard which is Gamakay K61, is it possible to add it to QMK? I would like to rebind keys in it. On box it says ARM 33bit mcu & led controller. 

I would love to see it added to QMK

**Comment by zvecr** [comment] 2022-01-20 21:23
Duplicate of qmk/qmk_firmware#15881

**Closed as completed by zvecr** 2022-01-20 21:23 UTC
Labels: enhancement
