### ISSUE TITLE
[Bug] loading of keyboard_list.json fails with CERT_DATE_INVALID response

### ISSUE THREAD

**Issue by kgstaley** [qmk/qmk.fm_old#153] opened 2022-03-03 00:44 UTC
### Describe the Bug

When trying to access the config.qmk.fm/#/ webpage, the initial fetch of the keyboard lists JSON fails. 

![image](https://user-images.githubusercontent.com/35789718/156474208-c460ff7b-103d-4e53-9118-4e5f7cb0f785.png)

### Additional Context?

Have tried numerous times over the day to access and tried to access from different machines, as well. Same result.

**Comment by zvecr** [comment] 2022-03-03 09:45
Duplicate of https://github.com/qmk/qmk_configurator/issues/1093

**Closed as completed by zvecr** 2022-03-03 09:45 UTC
Labels: bug
