### ISSUE TITLE
[Feature Request]  KBDPad MK III Firmware Support

### ISSUE THREAD

**Issue by jumblinjack** [qmk/qmk.fm_old#163] opened 2022-12-01 19:54 UTC
### Description

Hello!
I'm currently trying to change the firmware on my KBDPad MK II keypad, but it seems they updated the pcb with firmware for a mk III and the MK II option in the configurator doesn't flash properly and needs the new firmware from the website. https://kbdfans.com/products/gb-kbdpad-markii-mechanical-keyboard-kit
Would it be possible to add the new firmware to the site? 
Thank you!

**Comment by zvecr** [comment] 2022-12-01 22:16
Duplicate of qmk/qmk_firmware#19017

**Closed as not planned by zvecr** 2022-12-01 22:16 UTC
Labels: enhancement
